### ISSUE TITLE
https://terrain.party/ problem

### ISSUE THREAD

**Issue by doman93** [AS4SR/general_info#11]
https://terrain.party/ cannot export the output file.
Error message : An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command

**Comment by MatthewVerbryke** [comment]
Hello, 

Yeah, I believe the terrain.party app no longer works and/or isn't being maintained (at least I haven't had success with it in a while). 

Unfortunately, you'll probably need to use a different source for heightmaps. As long as the image is a grayscale image which follows the rules outlined in the tutorial, it should work with Gazebo.

**Comment by MatthewVerbryke** [comment]
I modified the gazebo terrain generation tutorial to remove the references to terrain party, since it no longer seems to be functional.
