### ISSUE TITLE
Basic ROS MoveIt! and Gazebo Integration--about adding the controller.yaml file

### ISSUE THREAD

**Issue by XiaoshanLin9701** [AS4SR/general_info#7]
Hi, in the tutorial **Basic ROS MoveIt! and Gazebo Integration** you say that we need to add a controllers.yaml file in the moveIt! config directory. But after I generate the moveIt config package using MoveIt! Setup Assistant, I found that there is a file named ros_controllers.yaml in the config directory. **Do I still need to add a controllers.yaml to the config directory?**The content of the file is as following:

kuka_kr210:
\# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
\# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
\# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
    sim_control_mode: 1  # 0: position, 1: velocity
\# Publish all joint states
\# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    []
  kuka_position_controller:
    type: position_controllers/JointPositionController
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
    gains:
      joint_a1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_a2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_a3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_a4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_a5:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_a6:
        p: 100
        d: 1
        i: 1
        i_clamp: 1

**Comment by MatthewVerbryke** [comment]
Which version of ROS are you using?

**Comment by XiaoshanLin9701** [comment]
Hi, I am using kinetic. I guess controllers.yaml is still needed, right?

**Comment by MatthewVerbryke** [comment]
Does MoveIt! work with Gazebo without manually adding controllers.yaml? If so they may have updated the Setup Assistant to take care of this step automatically.

**Comment by XiaoshanLin9701** [comment]
I found that controllers.yaml is still required. The robot works well in gazebo. Thank you so much.
