### ISSUE TITLE
Gazebo with Moveit Question

### ISSUE THREAD

**Issue by melvinma** [AS4SR/general_info#8]
Hi, thank you very much for [the MoveIt / Gazebo integration article](https://github.com/AS4SR/general_info/wiki/Basic-ROS-MoveIt!-and-Gazebo-Integration) . I think I got lost at the end - how exactly Gazebo is showing the robot. Was the robot URDF containing "world" coordinates of the robot? 

In other words, typically, Gazebo creates robots using the following 

> \<node name="spawn_gazebo_model" pkg="gazebo_ros" type="spawn_model" args="-urdf -param robot_description -model robot -x 60 -y -374 -z 0.1" respawn="false" output="screen" />

Where this function showing up the moveit/gazebo code? 

Thank you again!

**Comment by cmcghan** [comment]
There is an assumption here that you already have a world file and launch file that spawns your robot, a la:

roslaunch YOURROBOT_gazebo YOURROBOT_world.launch

The process for creating the initial 'spawn robot' file(s) is not given as part of the tutorial directly. (This tutorial covers the Gazebo linking process only.) However, an example of what you are seeking can be found at:
https://github.com/MatthewVerbryke/inmoov_ros/blob/master/inmoov_gazebo/launch/inmoov_world.launch
and
https://github.com/MatthewVerbryke/inmoov_ros/blob/master/inmoov_gazebo/worlds/inmoov.world

...but overall you are correct -- a spawn model call (potentially with x y z to position it) is necessary to spawn the robot here. The MoveIt files discussed in the wiki article do not handle this for you. I'll ask my student to add to this explanation, to make this more clear.

Thank you! :)

**Comment by MatthewVerbryke** [comment]
Which version of ROS are you using?

**Comment by melvinma** [comment]
I am using gazebo 9, ros / moveit Kinetic (Ubuntu 16)

**Comment by MatthewVerbryke** [comment]
Okay, then what cmcghan says is correct, in that you need to create a separate file to launch Gazebo (your typical launch file to spawn the URDF in a Gazebo world) before you launch the MoveIt launch file.

**Comment by melvinma** [comment]
Matthew, 

I guess I am not familiar with MoveIt and Gazebo enough yet. From what cmcghan and you were saying, it appears that if I need to do the following three steps on the Gazebo side:

- start the world;
- spawn the robot URDF node using gazebo_ros / gazebo_ros
- spawn the controllers node using controller_manager / spawner

Do you mind to explain a bit how these are connected to MoveIt? Are we actually running two robot nodes (one showing in Rviz and one showing on Gazebo)?

Thanks!

**Comment by MatthewVerbryke** [comment]
They are not directly connected to MoveIt as far as I can tell. Basically, you first launch Gazebo with the robot controllers , like what is normally done in Gazebo. Assuming you setup the controllers and other things correctly, MoveIt will look for the robot states coming out of Gazebo and the inputs for the robot controllers when you launch it afterwards, and then connect to them using ROS communications. This is why MoveIt needs to be launched after Gazebo and the robot controllers.

Also, Yes you will have RViz and Gazebo open at the same time (although you can run the system without RViz).
